contexts:
    default:
        brokers:
            - localhost:9092
        kafkaversion: 2.1.1
    stgdp7jk7l:
        brokers:
            - kafka.dgrvse.private.xyz:9092
        kafkaversion: 2.1.1
current-context: default
