# Shell variables
# Generated by 'wal'
wallpaper='None'

# Special
background='#1c2023'
foreground='#c7ccd1'
cursor='#c7ae95'

# Colors
color0='#1c2023'
color1='#c7ae95'
color2='#95c7ae'
color3='#aec795'
color4='#ae95c7'
color5='#c795ae'
color6='#95aec7'
color7='#c7ccd1'
color8='#747c84'
color9='#c7ae95'
color10='#95c7ae'
color11='#aec795'
color12='#ae95c7'
color13='#c795ae'
color14='#95aec7'
color15='#f3f4f5'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
