--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper=""

-- Special
background="#101419"
foreground="#b6beca"
cursor="#f5f5f5"

-- Colors
color0="#1c252c"
color1="#e05f65"
color2="#78DBA9"
color3="#f1cf8a"
color4="#70a5eb"
color5="#c68aee"
color6="#74bee9"
color7="#dee1e6"
color8="#384148"
color9="#fc7b81"
color10="#94f7c5"
color11="#ffeba6"
color12="#8cc1ff"
color13="#e2a6ff"
color14="#90daff"
color15="#fafdff"
