# Shell variables
# Generated by 'wal'
wallpaper=''

# Special
background='#101419'
foreground='#b6beca'
cursor='#f5f5f5'

# Colors
color0='#1c252c'
color1='#e05f65'
color2='#78DBA9'
color3='#f1cf8a'
color4='#70a5eb'
color5='#c68aee'
color6='#74bee9'
color7='#dee1e6'
color8='#384148'
color9='#fc7b81'
color10='#94f7c5'
color11='#ffeba6'
color12='#8cc1ff'
color13='#e2a6ff'
color14='#90daff'
color15='#fafdff'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
