--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="None"

-- Special
background="#1c2023"
foreground="#c7ccd1"
cursor="#c7ae95"

-- Colors
color0="#1c2023"
color1="#c7ae95"
color2="#95c7ae"
color3="#aec795"
color4="#ae95c7"
color5="#c795ae"
color6="#95aec7"
color7="#c7ccd1"
color8="#747c84"
color9="#c7ae95"
color10="#95c7ae"
color11="#aec795"
color12="#ae95c7"
color13="#c795ae"
color14="#95aec7"
color15="#f3f4f5"
