# Shell variables
# Generated by 'wal'
wallpaper='None'

# Special
background='#1d1f21'
foreground='#c5c8c6'
cursor='#c5c8c6'

# Colors
color0='#1d1f21'
color1='#cc6666'
color2='#b5bd68'
color3='#f0c674'
color4='#81a2be'
color5='#b294bb'
color6='#8abeb7'
color7='#c5c8c6'
color8='#969896'
color9='#cc6666'
color10='#b5bd68'
color11='#f0c674'
color12='#81a2be'
color13='#b294bb'
color14='#8abeb7'
color15='#ffffff'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
