theme = "plain"
icons = "awesome"

[[block]]
block = "focused_window"
max_width = 50
show_marks = "all"


[[block]]
block = "uptime"

[[block]]
block = "cpu"
interval = 1
format = "{utilization} {frequency}"


[[block]]
block = "custom"
command = "/home/madhur/.config/i3status-rust/cputemp.sh" # assumes fontawesome icons
interval = 1


[[block]]
block = "memory"
format_mem = " {mem_used_percents} ({mem_used}/{mem_total})"
format_swap = "{swap_used}/{swap_total}({swap_used_percents})"
display_type = "memory"
icons = true
clickable = true
interval = 5
warning_mem = 80
warning_swap = 80
critical_mem = 95
critical_swap = 95

[[block]]
block = "nvidia_gpu"
label = "RTX 3060"
show_memory = true
show_clocks = false
show_fan_speed = true
show_power_draw = false
show_utilization = true
interval = 1


[[block]]
block = "disk_space"
path = "/"
info_type = "used"
format = "{icon}  {percentage} ({used} / {total})"
alert_absolute = false
unit = "GB"
alert = 90
warning = 80

[[block]]
block = "net"
device = "wlp1s0f0u1"
format = "{ssid} {signal_strength} {ip} {speed_down;K*b} {speed_up;K*b}"
interval = 5


[[block]]
block = "sound"
format = "{output_name} {volume}"

[block.mappings]
"alsa_output.usb-Microsoft_Microsoft_LifeChat_LX-6000-00.analog-stereo" = "🎧"
"alsa_output.pci-0000_05_00.1.hdmi-stereo" = "🔈"
"alsa_output.pci-0000_05_00.1.hdmi-stereo-extra2" = "🔈"

[[block]]
block = "custom"
command = "echo \uf011" # assumes fontawesome icons
on_click = "rofi -modi 'Powermenu:/home/madhur/.config/rofi/powermenu.sh' -theme /home/madhur/.config/rofi/powermenu.rasi -show Powermenu -icon-theme Papirus"
interval = "once"

[[block]]
block = "time"
interval = 5
format = "%a %d %b %R"

